name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-django selenium flake8

      # ──────────────────────────────────────────────────────────────
      # Linter no bloqueante (si hay avisos, flake8 devuelve 0)
      # ──────────────────────────────────────────────────────────────
      - name: Linter (flake8)
        run: |
          flake8 . --exit-zero
      # ──────────────────────────────────────────────────────────────

      - name: Migraciones y pruebas (pytest)
        run: |
          python manage.py migrate --noinput
          pytest -q

  smoke:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render app (reintentos)
        run: |
          for i in {1..6}; do
            STATUS=$(curl -o /dev/null -s -w "%{http_code}" -L https://ci-cd-7hmy.onrender.com/todos/)
            echo "Intento $i - HTTP $STATUS"
            if [[ "$STATUS" =~ ^(200|301|302)$ ]]; then
              echo "Smoke test OK"
              exit 0
            fi
            sleep 5
          done
          echo "Smoke test failed: HTTP $STATUS"
          exit 1

