name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-django selenium flake8

      - name: Linter (flake8)
        run: flake8 .

      - name: Migraciones y pruebas (pytest)
        run: |
          python manage.py migrate --noinput
          pytest -q

  smoke:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render app
        run: |
          STATUS=$(curl -sw '%{http_code}' -o /dev/null https://ci-cd-7hmy.onrender.com/todos/)
          if [ "$STATUS" != "200" ]; then
            echo "Smoke test failed: HTTP $STATUS"
            exit 1
          fi
